# Fine-tune an LM on the enron text dataset.

dataset_args:
  # dataset_path: ../src/pii_leakage/extern/echr
  dataset_path: data/echr
  dataset_mode: undefended
  sample_duplication_rate: 1

trainer_args:
  output_dir: /storage/jyhong/projects/projects/PrivateLLM/pii_leakage/results/echr-gpt2-small-undefended/
  overwrite_output_dir: True
  save_steps: 750
  callback_after_n_steps: 750
  num_train_epochs: 4
  # batch size=32
  gradient_accumulation_steps: 8
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4

model_args:
  architecture: gpt2
  pre_trained: True   # Start from a pre-trained checkpoint

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False
